# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mgbudgetapp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('type', models.CharField(choices=[(0, 'Train'), (1, 'BuyDirectly'), (2, 'BuyCredits'), (3, 'ApproveTransaction'), (4, 'RegisterUser'), (5, 'RegisterProduct'), (6, 'Joonas')], max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField(default=0)),
                ('cardSkipperId', models.CharField(max_length=50)),
                ('registered', models.DateTimeField()),
                ('birthDate', models.DateTimeField()),
                ('level', models.CharField(choices=[('Unknown', 'Unknown'), ('Beginner', 'Beginner'), ('Advanced', 'Advanced'), ('Competition', 'Competition')], default='Unknown', max_length=100)),
                ('accessRule', models.ManyToManyField(to='mgbudgetapp.AccessRule')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('registered', models.DateTimeField()),
                ('lastEdit', models.DateTimeField()),
                ('ageRestriction', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('barcode', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgbudgetapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('details', models.CharField(max_length=300)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coach', to='mgbudgetapp.Fighter')),
                ('fighter', models.ManyToManyField(related_name='fighter', to='mgbudgetapp.Fighter')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgbudgetapp.Season')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', mgbudgetapp.fields.IntegerRangeField()),
                ('time', mgbudgetapp.fields.IntegerRangeField()),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField()),
                ('approved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved', to='mgbudgetapp.Fighter')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='mgbudgetapp.Fighter')),
                ('product', models.ManyToManyField(to='mgbudgetapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField()),
                ('lastEdit', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='trainingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgbudgetapp.TrainingType'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='weekSchema',
            field=models.ManyToManyField(to='mgbudgetapp.WeekSchema'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgbudgetapp.TrainingType'),
        ),
        migrations.AddField(
            model_name='season',
            name='weakSchema',
            field=models.ManyToManyField(to='mgbudgetapp.WeekSchema'),
        ),
    ]
